apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx-local
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx-local
    spec:
      volumes:
      - name: nginx-assets
        configMap:
          name: nginx-assets
      containers:
      - name: nginx
        image: nginx:1.10
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: nginx-assets
          mountPath: "/usr/share/nginx/html"
