apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx-us
  annotations:
    federation.kubernetes.io/replica-set-preferences: |
        {
            "rebalance": true,
            "clusters": {
                "us-central1-b": {
                    "minReplicas": 2,
                    "maxReplicas": 4,
                    "weight": 1
                }
            }
        }
spec:
  replicas: 4
  template:
    metadata:
      labels:
        region: nginx-us
    spec:
      volumes:
      - name: nginx-assets
        configMap:
          name: nginx-assets
      containers:
      - name: nginx
        image: nginx:1.10
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: nginx-assets
          mountPath: "/usr/share/nginx/html"
