apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-local
  name: nginx-local
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31315
    name: http
  selector:
    app: nginx-local
  type: NodePort
